spring.application.name=lombok

logging.level.com.example.lombok=trace

# logging file
logging.file.name=./log/app.log
logging.logback.rollingpolicy.file-name-pattern=./log/app.backup.%d{yyyy-MM-dd}.%i.gz
logging.logback.rollingpolicy.max-history=7
logging.logback.rollingpolicy.max-file-size=10KB
logging.logback.rollingpolicy.total-size-cap=1GB

